[pytest]
markers =
    smoke: тесты для быстрого дымового тестирования
    regression: полные регрессионные тесты
    api: тесты, взаимодействующие с API
    slow: медленные тесты, которые можно пропускать при быстром прогоне
    database: тесты, требующие доступа к базе данных
    ui: тесты пользовательского интерфейса